name: printer_test
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  queue: ^3.1.0
  printing: ^5.11.0
  pdf: any 
  hive: ^2.2.3
  rxdart: ^0.27.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  path_provider: ^2.0.8
  web_socket_channel: ^2.4.0
  launch_at_startup: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/Dana-FaNum-Regular.ttf
